### PR TITLE
Localized and Migrate to .Net Core 1.1 and VS 2017

### PR DESCRIPTION
**Pull request by OmidID**
First commit of localized and Migrate to .Net Core 1.1 and VS 2017
Web project was localized except Tag Helpers and BaseController in admin area

Core, Admin project remain

### CODE REVIEW

**Comment by OmidID** [comment]
Hello @scheshan 
Are you interest to localize this project? 
Almost done. the only remain parts are Services and Models in DotNetBlog.Core project, in this week i'll finish remains part.

**Comment by OmidID** [comment]
@scheshan Your application fully localized please let me know if you are interest or not !

**Comment by scheshan** [comment]
Thanks very much for your work! And I'm so sorry for missing your messages. It sounds perfect to support multiple languages and thank you for implementing it. 
I just wonder if it's a good idea to merge so many resource files into one, or merge them group by projects? If so, I will finish in the next days.

**Comment by OmidID** [comment]
hello @scheshan :) thank you so much for your reply 
I have a bug in Installation part and i discover that at morning.
about the multiple resource files i flow the Microsoft document.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization
as you see in Admin panel i used one file in resource, actually i should split it to more 1 file because for each language we should have one file.
THANK AGAIN :)

**Comment by OmidID** [comment]
@scheshan Also we should find a solution for installation. i think it's better to have a UI Install Configuration.

**Comment by scheshan** [comment]
@OmidID I will add a installation page, I think I will finish it this weekend.

**Pull request merged**
