### PR TITLE
I had finished Theme Engine. Now we can developing new Themes #6

### PR DESCRIPTION
**Pull request by OmidID**

### CODE REVIEW

**Comment by OmidID** [comment]
@scheshan Looks i had conflict on Install file. As I see here I don't have access to Resolve the conflict. Please fix the problem and replace what you did in `~/Themes/default/Install/*`
THANKS ;)

**Comment by scheshan** [comment]
Dear @OmidID, I've merged the PR in command line.

**Comment by scheshan** [comment]
And I think the best way for us is to wait until the new .NET Core version is released. I've noticed that in .NET Core 2.0, there will be NET Standard 2.0 so we can use many old APIs that exist in .NET Framework. And in ASP.NET Core 2.0, there will be new features like Razor Page, new configurations in Startup class, It seems some of our code and logic will change in the upgrade.

**Comment by OmidID** [comment]
OK. i agree with you @scheshan 
Also I want to start implement Mobile App base on Xamarin.Forms for Admin.

**Pull request merged**
